DROP DATABASE IF EXISTS `QLHSSV_DB`;

CREATE DATABASE `QLHSSV_DB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `QLHSSV_DB`;

CREATE TABLE `QLHSSV_DB`.`users`
(
    id         INT(11) NOT NULL AUTO_INCREMENT,
    is_valid   TINYINT(1) NOT NULL DEFAULT '0',
    username   VARCHAR(255) NULL,
    password   VARCHAR(255) NULL,
    email      VARCHAR(255) NULL,
    is_admin   TINYINT(1) NOT NULL DEFAULT '0',
    is_teacher TINYINT(1) NOT NULL DEFAULT '0',
    is_student TINYINT(1) NOT NULL DEFAULT '0',
    created_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;